name: Build Project
on: push
jobs:
  runs-on: windows-latest
  steps:
    - name: Get repository
      uses: actions/checkout@v3
    - name: npm install
      run: npm ci
    - name: Build
      run: npm run build
