name: Build Project
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/*'
env:
  NODE_ENV: production
  GH_SECRET: 23
jobs:
  building:
    runs-on: windows-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Get env build
        run:
          echo "${{ env.NODE_ENV }}"
          echo "${{ env.GH_SECRET }}"
      - name: npm install
        run: npm ci
      - name: Build
        run: npm run build
  deploy:
    runs-on: windows-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Get env deploy
        run:
          echo "${{ env.NODE_ENV }}"
          echo "${{ env.GH_SECRET }}"
      - name: npm install
        run: npm ci
      - name: Build
        run: npm run build