name: Build Project
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/*'
jobs:
  building:
    runs-on: windows-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: npm install
        run: npm ci
      - name: Build
        run: npm run build